### ISSUE TITLE
Saving to file some lines will be cut off.

### ISSUE THREAD

**Issue by robertjones1** [dart-lang/logging#106]
I notice when saving the logs to a file that the beginning of the line can at time be cut off.

**Comment by KnucklesEQ** [comment]
I have had some problems with this issue, and I think the problem lies in trying to access the file concurrently. One possible solution that has worked for me is to simply append the file when you use "writeAsString":

```
final _logFile = File("/path/to/file/log.txt");

Logger.root.onRecord.listen((LogRecord record) {
    _logFile.writeAsStringSync(
      '${record.level.name}// '
      '${record.time}: ${record.message}\n',
      mode: FileMode.append,
      flush: true,
    );
  });
```

If it doesn't solve your problem, maybe the [synchronized](https://pub.dev/packages/synchronized) package could help. Idea picked from [stackoverflow](https://stackoverflow.com/questions/54958346/dart-file-writeasstring-method-does-not-write-to-file-if-await-is-not-done-imm).

**Comment by devoncarew** [comment]
@robertjones1 - it's not clear to me how this package would be involved in the issue. I suspect (as mentioned above) it may be a race condition in the code writing to disk. Can you provide more info on your repro steps?
