### ISSUE TITLE
Unable to change logging level dynamically

### ISSUE THREAD

**Issue by jagan999** [dart-lang/logging#44]
If I want to change the default root.level from WARNING to ALL through the app (like when a user wants to increase the logging level), updating the root.level to ALL does not start sending ALL messages to the listener unless the app is restarted. Is there a way to re-initialize the Logger at runtime without requiring a re-start?

**Comment by jamesderlin** [comment]
1. Changing logging levels dynamically already should work.
2. If the issue is that you're trying to set the level of a non-root `Logger` with `hierarchicalLoggingEnabled = false`, then that already throws `UnsupportedError`.

Is there anything that still needs to be fixed?  If so, please provide code to reproduce the issue.

**Comment by natebosch** [comment]
Closing as stale since this should be working. If you can provide a minimal reproduction where it isn't working we can revisit this.
