### ISSUE TITLE
make a non-null judgment of paremeter message in “void log” method

### ISSUE THREAD

**Issue by johnhollon** [dart-lang/logging#53]
Since the return value of null.toString() is "null", it‘s recommended to make a non-null judgment of paremeter message in “void log” method. Otherwise, when paremeter message is null, the LogRecord's message property will be assigned to the string "null".

由于null.toString()的返回值是"null"，建议在void log方法中对message进行非空判断，否则在message为null时，LogRecord的message属性会被赋值为字符串"null"。

**Comment by jamesderlin** [comment]
To clarify: are you requesting that the behavior of `Logger.info(null)`, `Logger.warning(null)`, etc. be changed?  If so, what do you want the new behavior to be?  Do you want `LogRecord.message` to be `null` instead of the string `'null'`?

**Comment by natebosch** [comment]
Closing for now, I think logging the string `'null'` is consistent and sensible. Trying to forward the `null` through `LogRecord.message` would not play nicely with null safe Dart since I suspect we will want the `message` field to be non-nullable.  Making it `String?` for the sake of the edge case where a log listener wants to treat `null` differently from `'null'` seems to me to add more noise than it's worth. If someone feels strongly about making `message` be a `String?` please comment and we can reconsider.
