### ISSUE TITLE
Linebreaks make the following logs output not with logger prefix

### ISSUE THREAD

**Issue by rockingdice** [dart-lang/logging#65]
If I output a log with "\n", the lines under the first line are not with logger prefix:

run code:
```
Logger.root.severe("Error Log:\nServer Error (500)";
```

get logs:
``` 
I/flutter (12268): SEVERE: 2019-08-10 10:27:37.543438: Error Log: 
I/flutter (12268): Server Error (500)
```

But I'm expecting to be this:
```
I/flutter (12268): SEVERE: 2019-08-10 10:27:37.543438: Error Log: 
I/flutter (12268): SEVERE: Server Error (500)
```
This is very useful if you use some colorful console plugins to colorize them using regexps.

Can there be a configurable option to show like that?

**Comment by jamesderlin** [comment]
`package:logging` doesn't print or format log messages.  There's a [request to provide a default `onRecord` handler](https://github.com/dart-lang/logging/issues/61), but otherwise splitting multiline messages would be the responsibility of whatever your `onRecord` callback is.

Conceivably `package:logging` could split multiline messages in advance and call `onRecord` multiple times.  However, if it did that, it still would not have quite the same output as what you expected.  Additionally, it would not be possible to distinguish between `Logger.root.severe('foo\nbar');` and `Logger.root.severe('foo'); Logger.root.severe('bar');`.  That would pose additional problems if, say, you wanted to log a stacktrace since you would not want to do that for each line.

**Comment by natebosch** [comment]
+1

We don't want to get overly complex with assuming how the author may want output to look. If the author writing the output wants to split on newlines they can do that without it being baked in to the logging package.
