### ISSUE TITLE
Drop the `zone` argument

### ISSUE THREAD

**Issue by natebosch** [dart-lang/logging#76]
I can't find any usage of `LogRecord.zone` except in one case to forward to [`log` from `dart:developer`](https://api.dart.dev/stable/2.7.1/dart-developer/log.html), which according to the comment might only take this argument because we did (a long time ago) in this package.

cc @jakemac53 - this seems like something that _could_ be useful and it doesn't add much complexity, but since it's not used and was surprising to me when I saw it in a method signature I'm tempted to deprecate and then drop it. What do you think?

**Comment by natebosch** [comment]
Another thing that makes me want to drop it - this is likely _very_ easy to use wrong, and would be fooled by extra unexpected levels of `runZoned` which are common enough to make this a sharp edge.

**Comment by jakemac53** [comment]
Sgtm, @sigmundch any idea the backstory on this?

**Comment by sigmundch** [comment]
Seems this was added 5 years ago in https://github.com/dart-lang/logging/commit/0a994a926d502bda0060a2507fba48611886fb07

The original change was from @mkustermann - maybe he can comment on whether it is still relevant.

**Comment by mkustermann** [comment]
@natebosch This is a very useful feature (as mentioned in a comment in 0a994a926d50) - it allows the consumer of log messages to know in which zone an error occurred.

For example a server which handles multiple concurrent http requests might want to group all log messages by http request. When consuming log messages from a `Logger` it is not possible to distinguish - logs of all requests would be mixed up.

By running each request inside it's own zone via `runZoned(() {...}, zoneValues: {#requestInfo: ...})` it is possible to associate the zone with request-specific information. The log consumer can then use the recorded zone to access the `requestInfo`. 

This has been super helpful for e.g. developing `pub.dartlang.org` - one can find all logs for a specific request.

/cc @jonasfj

**Comment by mkustermann** [comment]
Just to give an example:
```dart
final log = Logger('foo');

main() {
  log.onRecord.listen((msg) {
    assert(Zone.current == Zone.root);
    // ^--- This callback will run in the ROOT zone! 
  });

  runZoned(() {
    log.shout('Error');
    // ^--- We want to remember zone-specific information for this logging call
  }, zoneValues: { ... });
}
```

**Comment by natebosch** [comment]
> This is a very useful feature (as mentioned in a comment in [0a994a9](https://github.com/dart-lang/logging/commit/0a994a926d502bda0060a2507fba48611886fb07)) - it allows the consumer of log messages to know in which zone an error occurred.

Should we consider the lack of use evidence that this isn't as useful as we thought? There are 0 usages internally except for one place forwarding to `log` from `dart:developer` which looks like it was done only because the API exists. I can reach out to the author and check whether they are using the zone or forwarding it because they can.

> This has been super helpful for e.g. developing `pub.dartlang.org` - one can find all logs for a specific request.

Can you link to the code for this? I looked in the `pub-dev` repo and couldn't find it.

> Just to give an example:

I understand what it _does_, I still don't understand who would use it. I haven't seen any evidence of anyone using zones for that pattern. I'd also worry that if someone _does_ try to use zones for that pattern that it would be a high potential for bugs.

**Comment by jonasfj** [comment]
> Can you link to the code for this? I looked in the pub-dev repo and couldn't find it.

See [setupAppEngineLogging](https://github.com/dart-lang/appengine/blob/711774ce84af2e26530cc8bc1a2e427ddbc73b6d/lib/src/server/logging_package_adaptor.dart#L26) in `package:appengine`.

From what I can see it logs to [`loggingService`](https://github.com/dart-lang/appengine/blob/711774ce84af2e26530cc8bc1a2e427ddbc73b6d/lib/src/logging.dart#L86) which is a _service scope_ thing. That is it's a variable that is always read from zone variables..

The _service scope_ concept originates from [package:gcloud](https://github.com/dart-lang/gcloud). If you're writing apps on top of the gcloud/appengine/shelf packages we have, you'll likely be using _service scopes_.

Whether using _service scopes_ for dependency injection is a good solution or not, is sort of an opinion. There are times when I think it's really nifty, and other times where it's perhaps a bit too dynamic (and causes hard to debug problems).

But using zones for request tracing and correlation of log entries to HTTP requests seems like exactly the kind of thing zones is ideal for. Maybe, zones can be used in smarter ways, but the idea of using zones to associating meta-data with log entries seems solid. Otherwise, we end up passing around a logging context.

**Comment by natebosch** [comment]
SGTM. Thanks!
